### ISSUE TITLE
error to charge caché "sporks.dat" fresh install

### ISSUE THREAD

**Issue by theburguet** [gamgsp/gspcoin#1]
![image](https://user-images.githubusercontent.com/57667436/200838018-be52c464-8c52-4fb8-a037-5951383432b0.png)

win 10 pro 64 bits
amd ryzen 5 3600x

**Comment by gamgsp** [comment]
Reinstate the wallet, delete all files and reinstall qt wallet.
Make sure to backup **wallet.dat** file
